#!/usr/bin/env bash

case $1 in
help)
    echo "Create your terraform.tfvars by running ./create-tfvars.sh [name]."
 ;;
status)
    if [[ -f terraform.tfvars ]]; then
        echo "terraform.tfvars already exists."
        cat terraform.tfvars
    else
        echo "terraform.tfvars does not exist."
    fi
 ;;
*)
    # Get the Billing Account
    BILLING_ACCOUNT=$(gcloud beta billing accounts list --format='value(ACCOUNT_ID)')
    # Get the logged in user account
    EMAIL=$(gcloud auth list --filter=status:ACTIVE --filter="-account ~ serviceaccount"  --format='value(ACCOUNT)')
    
    echo "" > terraform.tfvars
    echo "## This section has been auto-generated by ./create-tfvars.sh  ##" >> terraform.tfvars
    echo "email           = \"$EMAIL\"" >> terraform.tfvars
    echo "billing_account = \"$BILLING_ACCOUNT\"" >> terraform.tfvars
    echo "name            = \"$1\"" >> terraform.tfvars
    echo "## This section has been auto-generated by ./create-tfvars.sh  ##" >> terraform.tfvars
    cat terraform.tfvars
esac
